[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"

[[plugins]]
  package = "@netlify/plugin-astro"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  function = "edge"
  path = "/edge/*"

[images]
  remote_images = ["https://res.cloudinary.com/dq9xmts6p/.*"]
