[images]
  remote_images = ["https://res.cloudinary.com/dq9xmts6p/.*"]

[[plugins]]
  package = "netlify-plugin-bundle-env"
  [plugins.inputs]
    directories = [
      "dist/server",
      "dist/client"
    ]
    exclude = [
      "node_modules/**"
    ]

[[plugins]]
  package = "netlify-plugin-fetch-feeds"
  [plugins.inputs]
    dataDir = "src/data"
    [[plugins.inputs.feeds]]
      name = "dailydev"
      url = "https://daily.dev/blog/rss.xml"
      ttl = 3600

[build]
  command = "mkdir -p src/data && npm run build"
