[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    dataDir = "src/_data"

    [[plugins.inputs.feeds]]
      name = "example"
      url = "https://example.com/feed.xml"
      ttl = 3600
