[images]
  remote_images = ["https://res.cloudinary.com/dq9xmts6p/.*"]

[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    dataDir = "src/_data"

    [[plugins.inputs.feeds]]
      name = "dailydev"
      url = "https://daily.dev/blog/rss.xml"
      ttl = 3600
